version: "3"
services:
        mssql-db:
                image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
                container_name: mssqldb
                ports:
                        - "1433:1433"
                environment:
                        ACCEPT_EULA: y
                        SA_PASSWORD: P@ssw0rd 
                        MSSQL_PID: Express
                        MSSQL_COLLATION: Polish_CI_AS
                volumes:
                        - ./db:/mssqldb
        adminer:
                build: ./adminer
                ports:
                        - 8080:8080
